---
  apiVersion: "v1"
  kind: "ReplicationController"
  metadata: 
    labels: 
      name: "kubedash"
    name: "kubedash"
    namespace: "kube-system"
  spec: 
    replicas: 1
    selector: 
      name: "kubedash"
    template: 
      metadata: 
        labels: 
          name: "kubedash"
      spec: 
        containers: 
          - 
            image: "gcr.io/google-containers/kubedash:v0.0.2"
            name: "kubedash"
            command: 
              - "/kubedash"
            volumeMounts: 
              - 
                name: "ssl-certs"
                mountPath: "/etc/ssl/certs"
                readOnly: true
        volumes: 
          - 
            name: "ssl-certs"
            hostPath: 
              path: "/etc/ssl/certs"

---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    labels: 
      name: "kubedash"
    name: "kubedash"
    namespace: "kube-system"
  spec:
    type: "LoadBalancer"
    ports: 
      - 
        port: 80
        targetPort: 8289
    selector: 
      name: "kubedash"
